services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sub_app
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    container_name: sub_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

